spring.application.name=PrompVault

spring.datasource.url = jdbc:mysql://localhost:3306/prompt-vault?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true

spring.datasource.username = promptvault
spring.datasource.password = promptvault

spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql= true
